# Generated by Django 3.1.12 on 2021-07-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('1', 'Applied'), ('2', 'Heard Back'), ('3', 'Interview Scheduled'), ('4', 'Interviewed'), ('5', 'Ghosted'), ('6', 'Denied'), ('7', 'Received Offer')], default='1', max_length=50),
        ),
    ]
