# Generated by Django 3.1.12 on 2021-07-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker_app', '0002_auto_20210730_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
